# Default configuration profile for the Research RAG assistant.
app:
  name: "research-rag"
  env: "dev"
  log_level: "INFO"

data:
  source_dir: "data/source"
  derived_dir: "data/derived"
  output_directory: "data/derived/relevance"

features:
  enable_web: true
  enable_cli: true
