# Default configuration profile for the Research RAG assistant.
app:
  name: "research-rag"
  env: "dev"
  log_level: "INFO"

providers:
  llm: "local"
  embeddings: "sentence-transformers"
  vector_store: "chromadb"

data:
  source_dir: "data/source"
  derived_dir: "data/derived"
  output_directory: "data/derived/relevance"

llm:
  provider: "local"
  model: "llama3"
  host: "http://localhost:11434"

features:
  enable_web: true
  enable_cli: true
